# coding: utf-8

"""
    faasnap

    FaaSnap API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.function import Function  # noqa: E501
from swagger_client.rest import ApiException


class TestFunction(unittest.TestCase):
    """Function unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFunction(self):
        """Test Function"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.function.Function()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
