# coding: utf-8

"""
    faasnap

    FaaSnap API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_functions_get(self):
        """Test case for functions_get

        """
        pass

    def test_functions_post(self):
        """Test case for functions_post

        """
        pass

    def test_invocations_post(self):
        """Test case for invocations_post

        """
        pass

    def test_metrics_get(self):
        """Test case for metrics_get

        """
        pass

    def test_net_ifaces_namespace_put(self):
        """Test case for net_ifaces_namespace_put

        """
        pass

    def test_snapshots_post(self):
        """Test case for snapshots_post

        """
        pass

    def test_snapshots_put(self):
        """Test case for snapshots_put

        """
        pass

    def test_snapshots_ss_id_mincore_get(self):
        """Test case for snapshots_ss_id_mincore_get

        """
        pass

    def test_snapshots_ss_id_mincore_patch(self):
        """Test case for snapshots_ss_id_mincore_patch

        """
        pass

    def test_snapshots_ss_id_mincore_post(self):
        """Test case for snapshots_ss_id_mincore_post

        """
        pass

    def test_snapshots_ss_id_mincore_put(self):
        """Test case for snapshots_ss_id_mincore_put

        """
        pass

    def test_snapshots_ss_id_patch(self):
        """Test case for snapshots_ss_id_patch

        """
        pass

    def test_snapshots_ss_id_reap_delete(self):
        """Test case for snapshots_ss_id_reap_delete

        """
        pass

    def test_snapshots_ss_id_reap_get(self):
        """Test case for snapshots_ss_id_reap_get

        """
        pass

    def test_snapshots_ss_id_reap_patch(self):
        """Test case for snapshots_ss_id_reap_patch

        """
        pass

    def test_ui_data_get(self):
        """Test case for ui_data_get

        """
        pass

    def test_ui_get(self):
        """Test case for ui_get

        """
        pass

    def test_vmms_post(self):
        """Test case for vmms_post

        """
        pass

    def test_vms_get(self):
        """Test case for vms_get

        """
        pass

    def test_vms_post(self):
        """Test case for vms_post

        """
        pass

    def test_vms_vm_id_delete(self):
        """Test case for vms_vm_id_delete

        """
        pass

    def test_vms_vm_id_get(self):
        """Test case for vms_vm_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
