# coding: utf-8

"""
    faasnap

    FaaSnap API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.invocation import Invocation  # noqa: E501
from swagger_client.rest import ApiException


class TestInvocation(unittest.TestCase):
    """Invocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvocation(self):
        """Test Invocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.invocation.Invocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
